#!/bin/bash -e
# Run simple tests and check for forgotten changes.
# To have this run automatically on `git push`, run:
#     pmi-data/.git$ rm -r hooks && ln -s ../git-hooks hooks

ci/test_pre_push.sh

UNTRACKED=`git ls-files --others --exclude-standard`
UNCOMMITTED=`git diff --name-only`
if [ "$UNTRACKED" -o "$UNCOMMITTED" ]
then
  echo "You have untracked or uncommitted files. Continue with push?"
  echo $UNTRACKED $UNCOMMITTED
  select yn in "Yes" "No"
  do
    case $yn in
      Yes ) break;;
      No  ) exit 1;;
    esac
  done
fi
