"""add unique constraint to dv biobank order id

Revision ID: 153f3cbf1b4e
Revises: 8b20451a84df
Create Date: 2019-03-12 11:08:23.120542

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '153f3cbf1b4e'
down_revision = '8b20451a84df'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'biobank_dv_order', ['biobank_order_id'])
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'biobank_dv_order', type_='unique')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

