"""change site to unicode text

Revision ID: 69453413dfc3
Revises: 995557d8098a
Create Date: 2018-07-11 14:20:54.392997

"""
from alembic import op
import sqlalchemy as sa
import model.utils


from participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from participant_enums import WithdrawalStatus, SuspensionStatus
from participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType
from participant_enums import MetricSetType, MetricsKey
from model.site_enums import SiteStatus, EnrollingStatus
from model.code import CodeType

# revision identifiers, used by Alembic.
revision = '69453413dfc3'
down_revision = '995557d809a8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site',
                    'directions',
                    existing_type=sa.String(1024),
                    type_=sa.UnicodeText(),
                    existing_nullable=True)

    op.alter_column('site',
                    'notes',
                    existing_type=sa.String(1024),
                    type_=sa.UnicodeText(),
                    existing_nullable=True)

    op.alter_column('site',
                    'notes_es',
                    existing_type=sa.String(1024),
                    type_=sa.UnicodeText(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site',
                    'directions',
                    existing_type=sa.UnicodeText(),
                    type_=sa.String(1024),
                    existing_nullable=True)

    op.alter_column('site',
                    'notes',
                    existing_type=sa.UnicodeText(),
                    type_=sa.String(1024),
                    existing_nullable=True)

    op.alter_column('site',
                    'notes_es',
                    existing_type=sa.UnicodeText(),
                    type_=sa.String(1024),
                    existing_nullable=True)
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

