"""Add codebook name

Revision ID: dd60027993cc
Revises: b9330da5511d
Create Date: 2017-02-28 12:54:58.919228

"""
from alembic import op
import sqlalchemy as sa
import model.utils


from participant_enums import HPOId, PhysicalMeasurementsStatus, QuestionnaireStatus
from participant_enums import MembershipTier
from model.code import CodeType

# revision identifiers, used by Alembic.
revision = 'dd60027993cc'
down_revision = 'b9330da5511d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_book', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('code_book', sa.Column('version', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_book', 'version')
    op.drop_column('code_book', 'name')
    # ### end Alembic commands ###
