# Configuration for main API service. Should be kept in sync with test.yaml.
# This file is concatenated at the beginning of app_(non)?prod.yaml (instead of
# using an "includes" since "includes" only imports some directives).

env_variables:
  RDR_CONFIG_PROVIDER: "rdr_service.config.GoogleCloudDatastoreConfigProvider"

runtime: python37
# app_base.yaml is concatenated to the beginning of this file for deployment.

instance_class: F2

