# Configuration for main API service. Should be kept in sync with test.yaml.

threadsafe: true
runtime: python27
api_version: 1

builtins:
- deferred: on  

handlers:
- url: /_ah/datastore_admin.*
  script: google.appengine.ext.datastore_admin.main
  login: admin  
  secure: always
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
- url: /.*
  script: main.app
# App data directory used to load static files in AppEngine; not used for actual serving.
- url: /app_data/.*
  login: admin
  static_dir: app_data
  application_readable: true
  
libraries:
- name: pycrypto
  version: 2.6
- name: protorpc
  version: 1.0
- name: MySQLdb
  version: "latest"
