application: pmi-rdr-api-test
version: 1
threadsafe: true
runtime: python27
api_version: 1

handlers:
# The endpoints handler must be mapped to /_ah/spi.
# Apps send requests to /_ah/api, but the endpoints service handles mapping
# those requests to /_ah/spi.
- url: /_ah/spi/.*
  script: main.api

libraries:
- name: pycrypto
  version: 2.6
- name: endpoints
  version: 1.0
- name: MySQLdb
  version: "latest"
