/* Create voc and cdm databases for use with RDR -> OMOP ETL. */

DROP DATABASE IF EXISTS voc;
CREATE DATABASE voc CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON voc.* TO 'rdr'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, INDEX, REFERENCES, CREATE TEMPORARY TABLES, CREATE VIEW ON voc.* TO 'alembic'@'%';

DROP DATABASE IF EXISTS cdm;
CREATE DATABASE cdm CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON cdm.* TO 'rdr'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, INDEX, REFERENCES, CREATE TEMPORARY TABLES, CREATE VIEW ON cdm.* TO 'alembic'@'%';
