"""removing_fields

Revision ID: ff96a7d18e0c
Revises: 549c5e0fea26
Create Date: 2024-08-28 15:36:36.777014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'ff96a7d18e0c'
down_revision = '549c5e0fea26'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_ppsc():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'notes')
    op.drop_column('site', 'scheduling_instructions')
    op.drop_column('site', 'url')
    op.drop_column('site', 'directions')
    op.drop_column('site', 'email')
    # ### end Alembic commands ###


def downgrade_ppsc():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('email', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('site', sa.Column('directions', mysql.VARCHAR(length=1028), nullable=True))
    op.add_column('site', sa.Column('url', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('site', sa.Column('scheduling_instructions', mysql.VARCHAR(length=1028), nullable=True))
    op.add_column('site', sa.Column('notes', mysql.VARCHAR(length=512), nullable=True))
    # ### end Alembic commands ###

