"""Initial models

Revision ID: b6b04802e3d1
Revises: 
Create Date: 2017-12-08 12:42:23.843603

"""
from alembic import op
import sqlalchemy as sa
import model.utils


from participant_enums import MetricSetType, MetricsKey

# revision identifiers, used by Alembic.
revision = 'b6b04802e3d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_set',
    sa.Column('metric_set_id', sa.String(length=50), nullable=False),
    sa.Column('metric_set_type', model.utils.Enum(MetricSetType), nullable=False),
    sa.PrimaryKeyConstraint('metric_set_id')
    )
    op.create_table('aggregate_metrics',
    sa.Column('metric_set_id', sa.String(length=50), nullable=False),
    sa.Column('metrics_key', model.utils.Enum(MetricsKey), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metric_set_id'], ['metric_set.metric_set_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_set_id', 'metrics_key', 'value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aggregate_metrics')
    op.drop_table('metric_set')
    # ### end Alembic commands ###
