CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS '${READONLY_DB_USER}'@'%' IDENTIFIED BY '${READONLY_PASSWORD}';
CREATE USER IF NOT EXISTS '${RDR_DB_USER}'@'%' IDENTIFIED BY '${RDR_PASSWORD}';
CREATE USER IF NOT EXISTS '${ALEMBIC_DB_USER}'@'%' IDENTIFIED BY '${RDR_PASSWORD}';

GRANT SELECT ON ${DB_NAME}.* TO '${READONLY_DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON ${DB_NAME}.* TO '${RDR_DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, INDEX, REFERENCES, CREATE TEMPORARY TABLES ON ${DB_NAME}.* TO '${ALEMBIC_DB_USER}'@'%';
