"""update sample_identifier to support 64 character strings

Revision ID: a4f79191f32f
Revises: 889f4c28cc2b
Create Date: 2025-10-08 11:14:06.375482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4f79191f32f'
down_revision = '889f4c28cc2b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_sample', 'sample_identifier',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64))
    op.alter_column('sms_n1_mc1', 'sample_identifier',
                    existing_type=mysql.VARCHAR(length=32),
                    type_=sa.String(length=64))
    # ### end Alembic commands ###


def downgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_sample', 'sample_identifier',
                    existing_type=mysql.VARCHAR(length=64),
                    type_=sa.String(length=32))
    op.alter_column('sms_n1_mc1', 'sample_identifier',
                    existing_type=mysql.VARCHAR(length=64),
                    type_=sa.String(length=32))

    # ### end Alembic commands ###

