"""update sample_identifier to support 64 character strings

Revision ID: a4f79191f32f
Revises: 889f4c28cc2b
Create Date: 2025-10-08 11:14:06.375482

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a4f79191f32f'
down_revision = '889f4c28cc2b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE nph.sms_n1_mc1 MODIFY COLUMN sample_identifier VARCHAR(64)')
    op.execute('ALTER TABLE nph.sms_sample MODIFY COLUMN sample_identifier VARCHAR(64)')
    # ### end Alembic commands ###


def downgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE nph.sms_n1_mc1 MODIFY COLUMN sample_identifier VARCHAR(32)')
    op.execute('ALTER TABLE nph.sms_sample MODIFY COLUMN sample_identifier VARCHAR(32)')
    # ### end Alembic commands ###

