"""migrations for PBRC_DLW

Revision ID: aff2e875b4ef
Revises: 04817233e930
Create Date: 2024-05-30 12:35:35.881040

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = 'aff2e875b4ef'
down_revision = '04817233e930'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_n1_mc1', sa.Column('body_weight_kg', sa.String(length=1024), nullable=True))
    op.add_column('sms_n1_mc1', sa.Column('dlw_dose_batch', sa.String(length=1024), nullable=True))
    op.add_column('sms_n1_mc1', sa.Column('dlw_dose_date_time', sa.String(length=1024), nullable=True))
    op.add_column('sms_n1_mc1', sa.Column('dlw_dose_grams', sa.String(length=1024), nullable=True))
    op.add_column('sms_sample', sa.Column('body_weight_kg', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_sample', 'body_weight_kg')
    op.drop_column('sms_n1_mc1', 'dlw_dose_grams')
    op.drop_column('sms_n1_mc1', 'dlw_dose_date_time')
    op.drop_column('sms_n1_mc1', 'dlw_dose_batch')
    op.drop_column('sms_n1_mc1', 'body_weight_kg')
    # ### end Alembic commands ###

