"""Created index on 'participant.biobank_id' field

Revision ID: e48c9b943dbf
Revises: 3d78e7cfe123
Create Date: 2023-01-29 16:37:41.805324

"""

# pylint: disable=unused-import
# pylint: disable=line-too-long
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = 'e48c9b943dbf'
down_revision = '3d78e7cfe123'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('consent_event_ibfk_1', 'consent_event', type_='foreignkey')
    op.drop_constraint('consent_event_ibfk_2', 'consent_event', type_='foreignkey')
    op.drop_constraint('consent_event_ibfk_3', 'consent_event', type_='foreignkey')
    op.create_foreign_key(None, 'consent_event', 'participant', ['participant_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'consent_event', 'consent_event_type', ['event_type_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'consent_event', 'participant_event_activity', ['event_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.drop_constraint('enrollment_event_ibfk_2', 'enrollment_event', type_='foreignkey')
    op.drop_constraint('enrollment_event_ibfk_3', 'enrollment_event', type_='foreignkey')
    op.drop_constraint('enrollment_event_ibfk_1', 'enrollment_event', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment_event', 'participant', ['participant_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'enrollment_event', 'participant_event_activity', ['event_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'enrollment_event', 'enrollment_event_type', ['event_type_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.drop_constraint('order_ibfk_1', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_3', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_4', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_5', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_6', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_2', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'site', ['amended_site'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'order', 'site', ['finalized_site'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'order', 'study_category', ['category_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'order', 'participant', ['participant_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'order', 'site', ['collected_site'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'order', 'site', ['created_site'], ['id'], source_schema='nph', referent_schema='nph')
    op.drop_constraint('ordered_sample_ibfk_2', 'ordered_sample', type_='foreignkey')
    op.drop_constraint('ordered_sample_ibfk_1', 'ordered_sample', type_='foreignkey')
    op.create_foreign_key(None, 'ordered_sample', 'order', ['order_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'ordered_sample', 'ordered_sample', ['parent_sample_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.drop_constraint('pairing_event_ibfk_1', 'pairing_event', type_='foreignkey')
    op.drop_constraint('pairing_event_ibfk_3', 'pairing_event', type_='foreignkey')
    op.drop_constraint('pairing_event_ibfk_4', 'pairing_event', type_='foreignkey')
    op.drop_constraint('pairing_event_ibfk_2', 'pairing_event', type_='foreignkey')
    op.create_foreign_key(None, 'pairing_event', 'participant', ['participant_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'pairing_event', 'participant_event_activity', ['event_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'pairing_event', 'site', ['site_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'pairing_event', 'pairing_event_type', ['event_type_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_index('participant_biobank_id', 'participant', ['biobank_id'], unique=False, schema='nph')
    op.drop_constraint('participant_event_activity_ibfk_1', 'participant_event_activity', type_='foreignkey')
    op.drop_constraint('participant_event_activity_ibfk_2', 'participant_event_activity', type_='foreignkey')
    op.create_foreign_key(None, 'participant_event_activity', 'activity', ['activity_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'participant_event_activity', 'participant', ['participant_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.drop_constraint('sample_export_ibfk_1', 'sample_export', type_='foreignkey')
    op.drop_constraint('sample_export_ibfk_2', 'sample_export', type_='foreignkey')
    op.create_foreign_key(None, 'sample_export', 'sample_update', ['sample_update_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.create_foreign_key(None, 'sample_export', 'biobank_file_export', ['export_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.drop_constraint('sample_update_ibfk_1', 'sample_update', type_='foreignkey')
    op.create_foreign_key(None, 'sample_update', 'ordered_sample', ['rdr_ordered_sample_id'], ['id'], source_schema='nph', referent_schema='nph')
    op.drop_constraint('study_category_ibfk_1', 'study_category', type_='foreignkey')
    op.create_foreign_key(None, 'study_category', 'study_category', ['parent_id'], ['id'], source_schema='nph', referent_schema='nph')
    # ### end Alembic commands ###


def downgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_category', schema='nph', type_='foreignkey')
    op.create_foreign_key('study_category_ibfk_1', 'study_category', 'study_category', ['parent_id'], ['id'])
    op.drop_constraint(None, 'sample_update', schema='nph', type_='foreignkey')
    op.create_foreign_key('sample_update_ibfk_1', 'sample_update', 'ordered_sample', ['rdr_ordered_sample_id'], ['id'])
    op.drop_constraint(None, 'sample_export', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'sample_export', schema='nph', type_='foreignkey')
    op.create_foreign_key('sample_export_ibfk_2', 'sample_export', 'biobank_file_export', ['export_id'], ['id'])
    op.create_foreign_key('sample_export_ibfk_1', 'sample_export', 'sample_update', ['sample_update_id'], ['id'])
    op.drop_constraint(None, 'participant_event_activity', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'participant_event_activity', schema='nph', type_='foreignkey')
    op.create_foreign_key('participant_event_activity_ibfk_2', 'participant_event_activity', 'activity', ['activity_id'], ['id'])
    op.create_foreign_key('participant_event_activity_ibfk_1', 'participant_event_activity', 'participant', ['participant_id'], ['id'])
    op.drop_index('participant_biobank_id', table_name='participant', schema='nph')
    op.drop_constraint(None, 'pairing_event', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'pairing_event', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'pairing_event', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'pairing_event', schema='nph', type_='foreignkey')
    op.create_foreign_key('pairing_event_ibfk_2', 'pairing_event', 'site', ['site_id'], ['id'])
    op.create_foreign_key('pairing_event_ibfk_4', 'pairing_event', 'participant', ['participant_id'], ['id'])
    op.create_foreign_key('pairing_event_ibfk_3', 'pairing_event', 'participant_event_activity', ['event_id'], ['id'])
    op.create_foreign_key('pairing_event_ibfk_1', 'pairing_event', 'pairing_event_type', ['event_type_id'], ['id'])
    op.drop_constraint(None, 'ordered_sample', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'ordered_sample', schema='nph', type_='foreignkey')
    op.create_foreign_key('ordered_sample_ibfk_1', 'ordered_sample', 'order', ['order_id'], ['id'])
    op.create_foreign_key('ordered_sample_ibfk_2', 'ordered_sample', 'ordered_sample', ['parent_sample_id'], ['id'])
    op.drop_constraint(None, 'order', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'order', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'order', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'order', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'order', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'order', schema='nph', type_='foreignkey')
    op.create_foreign_key('order_ibfk_2', 'order', 'site', ['created_site'], ['id'])
    op.create_foreign_key('order_ibfk_6', 'order', 'site', ['finalized_site'], ['id'])
    op.create_foreign_key('order_ibfk_5', 'order', 'study_category', ['category_id'], ['id'])
    op.create_foreign_key('order_ibfk_4', 'order', 'site', ['collected_site'], ['id'])
    op.create_foreign_key('order_ibfk_3', 'order', 'participant', ['participant_id'], ['id'])
    op.create_foreign_key('order_ibfk_1', 'order', 'site', ['amended_site'], ['id'])
    op.drop_constraint(None, 'enrollment_event', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'enrollment_event', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'enrollment_event', schema='nph', type_='foreignkey')
    op.create_foreign_key('enrollment_event_ibfk_1', 'enrollment_event', 'enrollment_event_type', ['event_type_id'], ['id'])
    op.create_foreign_key('enrollment_event_ibfk_3', 'enrollment_event', 'participant_event_activity', ['event_id'], ['id'])
    op.create_foreign_key('enrollment_event_ibfk_2', 'enrollment_event', 'participant', ['participant_id'], ['id'])
    op.drop_constraint(None, 'consent_event', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'consent_event', schema='nph', type_='foreignkey')
    op.drop_constraint(None, 'consent_event', schema='nph', type_='foreignkey')
    op.create_foreign_key('consent_event_ibfk_3', 'consent_event', 'participant_event_activity', ['event_id'], ['id'])
    op.create_foreign_key('consent_event_ibfk_2', 'consent_event', 'participant', ['participant_id'], ['id'])
    op.create_foreign_key('consent_event_ibfk_1', 'consent_event', 'consent_event_type', ['event_type_id'], ['id'])
    # ### end Alembic commands ###
