"""Update bmi len to 32

Revision ID: f016544598f7
Revises: 511ebaf2239a
Create Date: 2023-12-18 16:21:43.636185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f016544598f7'
down_revision = '511ebaf2239a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_sample', 'bmi',
               existing_type=mysql.VARCHAR(length=4),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_nph():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_sample', 'bmi',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###

