"""removing version number from health data stream field

Revision ID: 03bb7f00c254
Revises: 3d95302cfb96
Create Date: 2023-07-05 09:04:19.110811

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql

from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = '03bb7f00c254'
down_revision = '3d95302cfb96'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    op.execute("""
        ALTER TABLE rdr.participant_summary
        CHANGE health_data_stream_sharing_status_v_3_1 health_data_stream_sharing_status smallint(6)
            GENERATED ALWAYS AS (
                (case
                    when `is_ehr_data_available` then 3
                    when `was_ehr_data_available` then 2
                    when `was_participant_mediated_ehr_available` then 2
                    else 1
                end)
            ) STORED,
        CHANGE health_data_stream_sharing_status_v_3_1_time health_data_stream_sharing_status_time datetime
            GENERATED ALWAYS AS (
                nullif(
                    greatest(
                        coalesce(`ehr_update_time`,0),
                        coalesce(`latest_participant_mediated_ehr_receipt_time`,0)
                    ),
                    0
                )
            ) STORED;
    """)


def downgrade_rdr():
    op.execute("""
        ALTER TABLE rdr.participant_summary
        CHANGE health_data_stream_sharing_status health_data_stream_sharing_status_v_3_1 smallint(6)
            GENERATED ALWAYS AS (
                (case
                    when `is_ehr_data_available` then 3
                    when `was_ehr_data_available` then 2
                    when `was_participant_mediated_ehr_available` then 2
                    else 1
                end)
            ) STORED,
        CHANGE health_data_stream_sharing_status_time health_data_stream_sharing_status_v_3_1_time datetime
            GENERATED ALWAYS AS (
                nullif(
                    greatest(
                        coalesce(`ehr_update_time`,0),
                        coalesce(`latest_participant_mediated_ehr_receipt_time`,0)
                    ),
                    0
                )
            ) STORED;
    """)


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

