"""adding 2sal0 fields

Revision ID: 04611c0c7caa
Revises: 2a0cc5df5d49
Create Date: 2024-03-18 08:41:06.870467

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql

from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = '04611c0c7caa'
down_revision = '2a0cc5df5d49'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    op.execute("""
        alter table participant_summary
        add column (
            sample_order_status_2sal0 smallint DEFAULT NULL,
            sample_order_status_2sal0_time datetime DEFAULT NULL,
            sample_status_2sal0 smallint DEFAULT NULL,
            sample_status_2sal0_time datetime DEFAULT NULL,
        );
    """)


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_summary', 'sample_status_2sal0_time')
    op.drop_column('participant_summary', 'sample_status_2sal0')
    op.drop_column('participant_summary', 'sample_order_status_2sal0_time')
    op.drop_column('participant_summary', 'sample_order_status_2sal0')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

