"""deidentify work zip

Revision ID: 060dba019a3a
Revises: 04564bf1b5e8
Create Date: 2018-01-04 09:51:00.885405

"""

# revision identifiers, used by Alembic.
revision = "060dba019a3a"
down_revision = "04564bf1b5e8"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    pass


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
