"""

Revision ID: 061dc1adde35
Revises: d5e7affa8201
Create Date: 2021-03-05 14:25:59.729392

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = '061dc1adde35'
down_revision = 'd5e7affa8201'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_gc_validation_metrics', sa.Column('drc_call_rate', sa.String(length=255), nullable=True))
    op.add_column('genomic_gc_validation_metrics', sa.Column('drc_contamination', sa.String(length=255), nullable=True))
    op.add_column('genomic_gc_validation_metrics', sa.Column('drc_fp_concordance', sa.String(length=255), nullable=True))
    op.add_column('genomic_gc_validation_metrics', sa.Column('drc_mean_coverage', sa.String(length=255), nullable=True))
    op.add_column('genomic_gc_validation_metrics', sa.Column('drc_sex_concordance', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_gc_validation_metrics', 'drc_sex_concordance')
    op.drop_column('genomic_gc_validation_metrics', 'drc_mean_coverage')
    op.drop_column('genomic_gc_validation_metrics', 'drc_fp_concordance')
    op.drop_column('genomic_gc_validation_metrics', 'drc_contamination')
    op.drop_column('genomic_gc_validation_metrics', 'drc_call_rate')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
