"""Cascade metrics deletes

Revision ID: 0cc3557c43d0
Revises: 3d4a6433e26d
Create Date: 2017-05-04 11:28:25.951742

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0cc3557c43d0"
down_revision = "3d4a6433e26d"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("metrics_bucket_ibfk_1", "metrics_bucket", type_="foreignkey")
    op.create_foreign_key(
        None, "metrics_bucket", "metrics_version", ["metrics_version_id"], ["metrics_version_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "metrics_bucket", type_="foreignkey")
    op.create_foreign_key(
        "metrics_bucket_ibfk_1", "metrics_bucket", "metrics_version", ["metrics_version_id"], ["metrics_version_id"]
    )
    # ### end Alembic commands ###
