"""adding_nullable_incentives

Revision ID: 136e4ea3caa2
Revises: c54b4d4ba8f8
Create Date: 2022-05-05 15:07:05.051978

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '136e4ea3caa2'
down_revision = 'c54b4d4ba8f8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant_incentives', 'amount',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=True)
    op.alter_column('participant_incentives', 'created_by',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('participant_incentives', 'incentive_type',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('participant_incentives', 'occurrence',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant_incentives', 'occurrence',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('participant_incentives', 'incentive_type',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('participant_incentives', 'created_by',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('participant_incentives', 'amount',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=False)
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
