"""create_metadata_table

Revision ID: 15c0ea24d179
Revises: 39f421efaa73
Create Date: 2020-03-25 10:48:35.049494

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


# revision identifiers, used by Alembic.
revision = '15c0ea24d179'
down_revision = '39f421efaa73'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created', rdr_service.model.utils.UTCDateTime6(fsp=6), nullable=True),
                    sa.Column('modified', rdr_service.model.utils.UTCDateTime6(fsp=6), nullable=True),
                    sa.Column('key', sa.String(length=255), nullable=False),
                    sa.Column('str_value', sa.String(length=500), nullable=True),
                    sa.Column('int_value', sa.Integer(), nullable=True),
                    sa.Column('date_value', rdr_service.model.utils.UTCDateTime6(fsp=6), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute('ALTER TABLE workbench_workspace MODIFY scientific_approaches VARCHAR(1000);')
    op.execute('ALTER TABLE workbench_workspace MODIFY intend_to_study VARCHAR(1000);')
    op.execute('ALTER TABLE workbench_workspace MODIFY findings_from_study VARCHAR(1000);')
    op.execute('ALTER TABLE workbench_workspace_history MODIFY scientific_approaches VARCHAR(1000);')
    op.execute('ALTER TABLE workbench_workspace_history MODIFY intend_to_study VARCHAR(1000);')
    op.execute('ALTER TABLE workbench_workspace_history MODIFY findings_from_study VARCHAR(1000);')
    op.execute('ALTER TABLE mayolink_create_order_history MODIFY request_test_code VARCHAR(500);')
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE mayolink_create_order_history MODIFY request_test_code VARCHAR(80);')
    op.execute('ALTER TABLE workbench_workspace MODIFY scientific_approaches VARCHAR(500);')
    op.execute('ALTER TABLE workbench_workspace MODIFY intend_to_study VARCHAR(500);')
    op.execute('ALTER TABLE workbench_workspace MODIFY findings_from_study VARCHAR(500);')
    op.execute('ALTER TABLE workbench_workspace_history MODIFY scientific_approaches VARCHAR(500);')
    op.execute('ALTER TABLE workbench_workspace_history MODIFY intend_to_study VARCHAR(500);')
    op.execute('ALTER TABLE workbench_workspace_history MODIFY findings_from_study VARCHAR(500);')
    op.drop_table('metadata')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
