"""Add order info

Revision ID: 272c7585b868
Revises: 4e8daad637a6
Create Date: 2017-06-22 10:21:59.098063

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "272c7585b868"
down_revision = "4e8daad637a6"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("biobank_order", sa.Column("collected_site_id", sa.Integer(), nullable=True))
    op.add_column("biobank_order", sa.Column("collected_username", sa.String(length=255), nullable=True))
    op.add_column("biobank_order", sa.Column("processed_site_id", sa.Integer(), nullable=True))
    op.add_column("biobank_order", sa.Column("processed_username", sa.String(length=255), nullable=True))
    op.add_column("biobank_order", sa.Column("source_username", sa.String(length=255), nullable=True))
    op.create_foreign_key(None, "biobank_order", "site", ["processed_site_id"], ["site_id"])
    op.create_foreign_key(None, "biobank_order", "site", ["collected_site_id"], ["site_id"])
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "biobank_order", type_="foreignkey")
    op.drop_constraint(None, "biobank_order", type_="foreignkey")
    op.drop_column("biobank_order", "source_username")
    op.drop_column("biobank_order", "processed_username")
    op.drop_column("biobank_order", "processed_site_id")
    op.drop_column("biobank_order", "collected_username")
    op.drop_column("biobank_order", "collected_site_id")
    # ### end Alembic commands ###
