"""CVL Fields and genomic state.

Revision ID: 31d9bc8bcc95
Revises: 16452fdb1334
Create Date: 2020-05-13 11:05:56.537388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from rdr_service.model.utils import Enum
from rdr_service.genomic_enums import GenomicWorkflowState

# revision identifiers, used by Alembic.
revision = '31d9bc8bcc95'
down_revision = '16452fdb1334'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_set_member', sa.Column('cvl_aw1c_manifest_job_run_id', sa.Integer(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('cvl_aw1c_manifest_job_run_id', sa.Integer(), nullable=True))

    op.add_column('genomic_set_member', sa.Column('cvl_aw1cf_manifest_job_run_id', sa.Integer(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('cvl_aw1cf_manifest_job_run_id', sa.Integer(), nullable=True))

    op.add_column('genomic_set_member', sa.Column('cvl_w1_manifest_job_run_id', sa.Integer(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('cvl_w1_manifest_job_run_id', sa.Integer(), nullable=True))

    op.add_column('genomic_set_member', sa.Column('cvl_w2_manifest_job_run_id', sa.Integer(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('cvl_w2_manifest_job_run_id', sa.Integer(), nullable=True))

    op.add_column('genomic_set_member', sa.Column('cvl_w3_manifest_job_run_id', sa.Integer(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('cvl_w3_manifest_job_run_id', sa.Integer(), nullable=True))

    op.add_column('genomic_set_member', sa.Column('cvl_w4_manifest_job_run_id', sa.Integer(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('cvl_w4_manifest_job_run_id', sa.Integer(), nullable=True))

    op.add_column('genomic_set_member', sa.Column('cvl_w4f_manifest_job_run_id', sa.Integer(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('cvl_w4f_manifest_job_run_id', sa.Integer(), nullable=True))

    op.add_column('genomic_set_member', sa.Column('genomic_workflow_state', Enum(GenomicWorkflowState), nullable=True))
    op.add_column('genomic_set_member_history',
                  sa.Column('genomic_workflow_state', Enum(GenomicWorkflowState), nullable=True))

    op.add_column('genomic_set_member', sa.Column('genomic_workflow_state_history', mysql.JSON(), nullable=True))
    op.add_column('genomic_set_member_history',
                  sa.Column('genomic_workflow_state_history', mysql.JSON(), nullable=True))

    op.drop_constraint('genomic_set_member_ibfk_6', 'genomic_set_member', type_='foreignkey')

    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['cvl_w4f_manifest_job_run_id'], ['id'])
    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['cvl_aw1c_manifest_job_run_id'], ['id'])
    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['cvl_aw1cf_manifest_job_run_id'], ['id'])
    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['cvl_w2_manifest_job_run_id'], ['id'])
    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['cvl_w3_manifest_job_run_id'], ['id'])
    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['cvl_w4_manifest_job_run_id'], ['id'])
    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['cvl_w1_manifest_job_run_id'], ['id'])

    op.drop_column('genomic_set_member', 'cvl_manifest_wgs_job_run_id')
    op.drop_column('genomic_set_member_history', 'cvl_manifest_wgs_job_run_id')
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_set_member', sa.Column('cvl_manifest_wgs_job_run_id', mysql.INTEGER(display_width=11),
                                                  autoincrement=False, nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('cvl_manifest_wgs_job_run_id', mysql.INTEGER(display_width=11),
                                                  autoincrement=False, nullable=True))

    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')
    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')
    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')
    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')
    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')
    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')
    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')

    op.create_foreign_key('genomic_set_member_ibfk_6', 'genomic_set_member', 'genomic_job_run', ['cvl_manifest_wgs_job_run_id'], ['id'])

    op.drop_column('genomic_set_member', 'genomic_workflow_state_history')
    op.drop_column('genomic_set_member_history', 'genomic_workflow_state_history')

    op.drop_column('genomic_set_member', 'genomic_workflow_state')
    op.drop_column('genomic_set_member_history', 'genomic_workflow_state')

    op.drop_column('genomic_set_member', 'cvl_w4f_manifest_job_run_id')
    op.drop_column('genomic_set_member_history', 'cvl_w4f_manifest_job_run_id')

    op.drop_column('genomic_set_member', 'cvl_w4_manifest_job_run_id')
    op.drop_column('genomic_set_member_history', 'cvl_w4_manifest_job_run_id')

    op.drop_column('genomic_set_member', 'cvl_w3_manifest_job_run_id')
    op.drop_column('genomic_set_member_history', 'cvl_w3_manifest_job_run_id')

    op.drop_column('genomic_set_member', 'cvl_w2_manifest_job_run_id')
    op.drop_column('genomic_set_member_history', 'cvl_w2_manifest_job_run_id')

    op.drop_column('genomic_set_member', 'cvl_w1_manifest_job_run_id')
    op.drop_column('genomic_set_member_history', 'cvl_w1_manifest_job_run_id')

    op.drop_column('genomic_set_member', 'cvl_aw1cf_manifest_job_run_id')
    op.drop_column('genomic_set_member_history', 'cvl_aw1cf_manifest_job_run_id')

    op.drop_column('genomic_set_member', 'cvl_aw1c_manifest_job_run_id')
    op.drop_column('genomic_set_member_history', 'cvl_aw1c_manifest_job_run_id')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
