"""rename indices in participant_summary table

Revision ID: 340ac70b1c2a
Revises: 9586837afe25
Create Date: 2022-12-07 12:00:10.624879

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = '340ac70b1c2a'
down_revision = '9586837afe25'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" and engine_name == "metrics":
        globals()["upgrade_%s" % engine_name]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" and engine_name == "metrics":
        globals()["downgrade_%s" % engine_name]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE participant_summary RENAME INDEX physical_measurements_finalized_site_id to clinic_physical_measurements_finalized_site_id;')
    op.execute('ALTER TABLE participant_summary RENAME INDEX physical_measurements_created_site_id to clinic_physical_measurements_created_site_id;')
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE participant_summary RENAME INDEX clinic_physical_measurements_finalized_site_id to physical_measurements_finalized_site_id;')
    op.execute('ALTER TABLE participant_summary RENAME INDEX clinic_physical_measurements_created_site_id to physical_measurements_created_site_id;')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
