"""add distinct visit counts

Revision ID: 3513057132ca
Revises: ed28b84f061e
Create Date: 2019-03-01 16:36:41.722682

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3513057132ca"
down_revision = "ed28b84f061e"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participant_summary", sa.Column("number_distinct_visits", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant_summary", "number_distinct_visits")
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
