"""add genomic_set_member.aw2f_manifest_job_run_id

Revision ID: 355854d777d3
Revises: a2d41894a561
Create Date: 2021-06-22 11:08:51.988993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '355854d777d3'
down_revision = 'a2d41894a561'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_set_member', sa.Column('aw2f_manifest_job_run_id', sa.Integer(), nullable=True))
    op.drop_constraint('genomic_set_member_ibfk_27', 'genomic_set_member', type_='foreignkey')
    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['aw2f_manifest_job_run_id'], ['id'])
    op.drop_column('genomic_set_member', 'aw2f_file_processed_id')
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_set_member', sa.Column('aw2f_file_processed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')
    op.create_foreign_key('genomic_set_member_ibfk_27', 'genomic_set_member', 'genomic_file_processed', ['aw2f_file_processed_id'], ['id'])
    op.drop_column('genomic_set_member', 'aw2f_manifest_job_run_id')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
