"""removing stored sample tmp table

Revision ID: 37bac919059e
Revises: 061dc1adde35
Create Date: 2021-03-10 16:13:28.497174

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = '37bac919059e'
down_revision = '061dc1adde35'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass



def upgrade_rdr():
    op.drop_index(op.f('ix_biobank_stored_sample_status_import_tmp_sample_id'), table_name='biobank_stored_sample_status_import_tmp')
    op.drop_index(op.f('ix_biobank_stored_sample_status_import_tmp_external_participant_id'), table_name='biobank_stored_sample_status_import_tmp')
    op.drop_table('biobank_stored_sample_status_import_tmp')


def downgrade_rdr():
    op.create_table('biobank_stored_sample_status_import_tmp',
        sa.Column('sample_family_id', sa.String(length=80), nullable=True),
        sa.Column('sample_id', sa.String(length=80), nullable=True),
        sa.Column('sample_storage_status', sa.String(length=80), nullable=True),
        sa.Column('sample_type', sa.String(length=80), nullable=True),
        sa.Column('parent_expected_volume', sa.String(length=80), nullable=True),
        sa.Column('sample_quantity', sa.String(length=80), nullable=True),
        sa.Column('sample_container_type', sa.String(length=80), nullable=True),
        sa.Column('sample_family_collection_date', rdr_service.model.utils.UTCDateTime(), nullable=True),
        sa.Column('sample_disposal_status', sa.String(length=80), nullable=True),
        sa.Column('sample_disposed_date', rdr_service.model.utils.UTCDateTime(), nullable=True),
        sa.Column('parent_sample_id', sa.String(length=80), nullable=True),
        sa.Column('sample_confirmed_date', rdr_service.model.utils.UTCDateTime(), nullable=True),
        sa.Column('external_participant_id', sa.String(length=80), nullable=True),
        sa.Column('test_code', sa.String(length=80), nullable=True),
        sa.Column('sample_treatment', sa.String(length=80), nullable=True),
        sa.Column('sample_family_create_date', rdr_service.model.utils.UTCDateTime(), nullable=True),
        sa.Column('sent_order_id', sa.String(length=80), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biobank_stored_sample_status_import_tmp_external_participant_id'), 'biobank_stored_sample_status_import_tmp', ['external_participant_id'], unique=False)
    op.create_index(op.f('ix_biobank_stored_sample_status_import_tmp_sample_id'), 'biobank_stored_sample_status_import_tmp', ['sample_id'], unique=False)


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
