"""creating additional ehr sharing fields

Revision ID: 3bd1cf3a498d
Revises: bbf2f8d73a96, 7cd998fccc27, 47fdbc544e62
Create Date: 2022-09-08 12:12:28.300529

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity, DigitalHealthSharingStatusV31
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = '3bd1cf3a498d'
down_revision = ('bbf2f8d73a96', '7cd998fccc27', '47fdbc544e62')
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE participant_summary
        ADD COLUMN health_data_stream_sharing_status_v_3_1 smallint(6) GENERATED ALWAYS AS ((case when is_ehr_data_available then 3 when was_ehr_data_available then 2 else 1 end)) STORED,
        ADD COLUMN health_data_stream_sharing_status_v_3_1_time datetime GENERATED ALWAYS AS (ehr_update_time) STORED
    """)

    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_summary', 'health_data_stream_sharing_status_v_3_1_time')
    op.drop_column('participant_summary', 'health_data_stream_sharing_status_v_3_1')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
