"""Adding HPO columns

Revision ID: 3d4a6433e26d
Revises: ae11bf43cab2
Create Date: 2017-04-28 09:55:09.728226

"""
from alembic import op
import sqlalchemy as sa
import model.utils


from participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus
from participant_enums import WithdrawalStatus, SuspensionStatus
from participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType
from model.code import CodeType

# revision identifiers, used by Alembic.
revision = '3d4a6433e26d'
down_revision = 'ae11bf43cab2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hpo', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('hpo', sa.Column('organization_type', model.utils.Enum(OrganizationType), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hpo', 'organization_type')
    op.drop_column('hpo', 'display_name')
    # ### end Alembic commands ###
