"""Adding HPO columns

Revision ID: 3d4a6433e26d
Revises: ae11bf43cab2
Create Date: 2017-04-28 09:55:09.728226

"""
import model.utils
import sqlalchemy as sa
from alembic import op

from rdr_service.participant_enums import OrganizationType

# revision identifiers, used by Alembic.
revision = "3d4a6433e26d"
down_revision = "ae11bf43cab2"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hpo", sa.Column("display_name", sa.String(length=255), nullable=True))
    op.add_column("hpo", sa.Column("organization_type", model.utils.Enum(OrganizationType), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hpo", "organization_type")
    op.drop_column("hpo", "display_name")
    # ### end Alembic commands ###
