"""genomic set member workflow modified

Revision ID: 415b87cb2eee
Revises: 848be944cda0
Create Date: 2020-09-01 12:33:14.950718

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '415b87cb2eee'
down_revision = '848be944cda0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_set_member', sa.Column('genomic_workflow_state_modified_time', sa.DateTime(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('genomic_workflow_state_modified_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    op.drop_column('genomic_set_member', 'genomic_workflow_state_modified_time')
    op.drop_column('genomic_set_member_history', 'genomic_workflow_state_modified_time')
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
