"""renaming to environmental exposures

Revision ID: 4dddd51685cb
Revises: c292a22a41a4, 281fd4037127, 8571eb776efc
Create Date: 2023-10-31 09:09:59.524361

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql

from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = '4dddd51685cb'
down_revision = ('c292a22a41a4', '281fd4037127', '8571eb776efc')
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    op.execute("""
        ALTER TABLE pediatric_data_log
        MODIFY COLUMN data_type enum('AGE_RANGE', 'ENVIRONMENTAL_HEALTH', 'ENVIRONMENTAL_EXPOSURES') NOT NULL
    """)
    op.execute("""
        UPDATE pediatric_data_log
        SET data_type = 'ENVIRONMENTAL_EXPOSURES'
        WHERE data_type = 'ENVIRONMENTAL_HEALTH'
    """)
    op.execute("""
        ALTER TABLE pediatric_data_log
        MODIFY COLUMN data_type enum('AGE_RANGE', 'ENVIRONMENTAL_EXPOSURES') NOT NULL
    """)


def downgrade_rdr():
    op.execute("""
        ALTER TABLE pediatric_data_log
        MODIFY COLUMN data_type enum('AGE_RANGE', 'ENVIRONMENTAL_HEALTH', 'ENVIRONMENTAL_EXPOSURES') NOT NULL
    """)
    op.execute("""
        UPDATE pediatric_data_log
        SET data_type = 'ENVIRONMENTAL_HEALTH'
        WHERE data_type = 'ENVIRONMENTAL_EXPOSURES'
    """)
    op.execute("""
        ALTER TABLE pediatric_data_log
        MODIFY COLUMN data_type enum('AGE_RANGE', 'ENVIRONMENTAL_HEALTH') NOT NULL
    """)


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

