"""Adding valueUri to QRA

Revision ID: 4e8daad637a6
Revises: 19687c270db8
Create Date: 2017-06-15 12:28:16.260816

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e8daad637a6"
down_revision = "19687c270db8"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questionnaire_response_answer", sa.Column("value_uri", sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questionnaire_response_answer", "value_uri")
    # ### end Alembic commands ###
