"""add_version_to_genomic_manifest_feedback

Revision ID: 56c49230d778
Revises: 7c0585790bc8
Create Date: 2021-08-30 12:55:08.914008

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '56c49230d778'
down_revision = '7c0585790bc8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_manifest_feedback', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_manifest_feedback', 'version')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
