"""Add Gem Pass to genomic set member

Revision ID: 67710db9e2e1
Revises: df221cca2299
Create Date: 2020-03-06 11:19:17.165251

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '67710db9e2e1'
down_revision = 'df221cca2299'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_set_member', sa.Column('gem_pass', sa.String(length=10), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('gem_pass', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_set_member', 'gem_pass')
    op.drop_column('genomic_set_member_history', 'gem_pass')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
