"""change site to unicode text

Revision ID: 69453413dfc3
Revises: 0a4ccc37472a
Create Date: 2018-07-11 14:20:54.392997

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "69453413dfc3"
down_revision = "0a4ccc37472a"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "site", "directions", existing_type=sa.String(1024), type_=sa.UnicodeText(), existing_nullable=True
    )

    op.alter_column("site", "notes", existing_type=sa.String(1024), type_=sa.UnicodeText(), existing_nullable=True)

    op.alter_column("site", "notes_es", existing_type=sa.String(1024), type_=sa.UnicodeText(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "site", "directions", existing_type=sa.UnicodeText(), type_=sa.String(1024), existing_nullable=True
    )

    op.alter_column("site", "notes", existing_type=sa.UnicodeText(), type_=sa.String(1024), existing_nullable=True)

    op.alter_column("site", "notes_es", existing_type=sa.UnicodeText(), type_=sa.String(1024), existing_nullable=True)
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
