"""

Revision ID: 6de7e8a83d66
Revises: e4eedba5965f
Create Date: 2021-06-04 14:16:31.680293

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6de7e8a83d66'
down_revision = 'e4eedba5965f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_incident', sa.Column('data_file_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_incident', 'data_file_path')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
