"""add aw3 job run id to genomic_set_member

Revision ID: 7029234abc61
Revises: d5d97368b14d
Create Date: 2020-08-03 13:46:15.629635

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7029234abc61'
down_revision = 'd5d97368b14d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_set_member', sa.Column('arr_aw3_manifest_job_run_id', sa.Integer(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('arr_aw3_manifest_job_run_id', sa.Integer(), nullable=True))

    op.add_column('genomic_set_member', sa.Column('wgs_aw3_manifest_job_run_id', sa.Integer(), nullable=True))
    op.add_column('genomic_set_member_history', sa.Column('wgs_aw3_manifest_job_run_id', sa.Integer(), nullable=True))

    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['arr_aw3_manifest_job_run_id'], ['id'])
    op.create_foreign_key(None, 'genomic_set_member', 'genomic_job_run', ['wgs_aw3_manifest_job_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')
    op.drop_constraint(None, 'genomic_set_member', type_='foreignkey')

    op.drop_column('genomic_set_member', 'wgs_aw3_manifest_job_run_id')
    op.drop_column('genomic_set_member_history', 'wgs_aw3_manifest_job_run_id')

    op.drop_column('genomic_set_member', 'arr_aw3_manifest_job_run_id')
    op.drop_column('genomic_set_member_history', 'arr_aw3_manifest_job_run_id')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
