"""Add column dsv2_survey_comments to workbench_researcher

Revision ID: 780892c15486
Revises: 3307fb034338
Create Date: 2022-07-05 10:31:10.393160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780892c15486'
down_revision = '3307fb034338'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbench_researcher', sa.Column('dsv2_survey_comments', sa.String(length=200), nullable=True))
    op.add_column('workbench_researcher_history', sa.Column('dsv2_survey_comments', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbench_researcher_history', 'dsv2_survey_comments')
    op.drop_column('workbench_researcher', 'dsv2_survey_comments')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
