"""Add ID verification fields to participant_summary

Revision ID: 7cd998fccc27
Revises: 11234f47671d
Create Date: 2022-08-26 12:52:18.154024

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = '7cd998fccc27'
down_revision = '11234f47671d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_summary', sa.Column('onsite_id_verification_site_id', sa.Integer(), nullable=True))
    op.add_column('participant_summary', sa.Column('onsite_id_verification_user', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'participant_summary', 'site', ['onsite_id_verification_site_id'], ['site_id'])
    op.execute(
        """UPDATE participant_summary ps
                INNER JOIN (
                    SELECT oiv.*
                    FROM onsite_id_verification oiv
                        JOIN (
                            SELECT MAX(verified_time) vt, participant_id
                            FROM onsite_id_verification
                            GROUP BY participant_id
                        ) max_vts ON oiv.participant_id = max_vts.participant_id
                        AND oiv.verified_time = max_vts.vt
                ) oiv_max_vts ON oiv_max_vts.participant_id = ps.participant_id
            SET ps.onsite_id_verification_user = oiv_max_vts.user_email,
                ps.onsite_id_verification_site_id = oiv_max_vts.site_id,
                ps.onsite_id_verification_visit_type = oiv_max_vts.visit_type,
                ps.last_modified = now()
        """
    )
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant_summary', type_='foreignkey')
    op.drop_column('participant_summary', 'onsite_id_verification_user')
    op.drop_column('participant_summary', 'onsite_id_verification_site_id')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
