"""Add order fields for DV

Revision ID: 80d36c1e37e2
Revises: 77422a4d8e14
Create Date: 2019-03-05 14:16:11.937122

"""
import model.utils
import sqlalchemy as sa
from alembic import op

from rdr_service.participant_enums import OrderStatus

# revision identifiers, used by Alembic.
revision = "80d36c1e37e2"
down_revision = "77422a4d8e14"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participant_summary", sa.Column("sample_order_status_dv_1sal2", model.utils.Enum(OrderStatus), nullable=True)
    )
    op.add_column(
        "participant_summary", sa.Column("sample_order_status_dv_1sal2_time", model.utils.UTCDateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant_summary", "sample_order_status_dv_1sal2_time")
    op.drop_column("participant_summary", "sample_order_status_dv_1sal2")
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
