"""generic prs consent validation tables

Revision ID: 90a6e2b8c0fb
Revises: 6829b893fdce
Create Date: 2026-07-17 07:49:50.346362

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql

from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = '90a6e2b8c0fb'
down_revision = '6829b893fdce'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prs_consent_response',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', rdr_service.model.utils.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('participant_id', sa.Integer(), nullable=True),
        sa.Column('signed_date', sa.Date(), nullable=True),
        sa.Column('consent_type', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['participant_id'], ['participant.participant_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prs_consent_response_consent_type'), 'prs_consent_response', ['consent_type'], unique=False)
    op.create_table('prs_consent_validation_result',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', rdr_service.model.utils.UTCDateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('prs_consent_response_id', sa.Integer(), nullable=True),
        sa.Column('is_valid', sa.Boolean(), nullable=True),
        sa.Column('ignore', sa.Boolean(), server_default=sa.text('0'), nullable=True),
        sa.ForeignKeyConstraint(['prs_consent_response_id'], ['prs_consent_response.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prs_consent_validation_error',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('prs_consent_validation_result_id', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(['prs_consent_validation_result_id'], ['prs_consent_validation_result.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prs_consent_validation_error')
    op.drop_table('prs_consent_validation_result')
    op.drop_index(op.f('ix_prs_consent_response_consent_type'), table_name='prs_consent_response')
    op.drop_table('prs_consent_response')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

