"""Add summary view

Revision ID: 9b70eae79af0
Revises: 272c7585b868
Create Date: 2017-06-26 13:19:56.594333

"""

# revision identifiers, used by Alembic.
revision = "9b70eae79af0"
down_revision = "272c7585b868"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_rdr():
    # View is replaced entirely in later migration.
    pass


def downgrade_rdr():
    pass
