"""add columns to metrics_enrollment_status_cache table

Revision ID: 9c957ce496bf
Revises: b662c5bb00cc
Create Date: 2019-05-31 11:14:30.217021

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "9c957ce496bf"
down_revision = "484c5d15ac06"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE metrics_enrollment_status_cache ADD COLUMN participant_count int(11) NOT NULL AFTER `registered_count`;"
    )
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metrics_enrollment_status_cache", "participant_count")
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
