"""removing_processing_field

Revision ID: a13126fcffb2
Revises: 42071b7a8c88, 5d980bf203fd
Create Date: 2023-05-01 16:17:05.723670

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a13126fcffb2'
down_revision = ('42071b7a8c88', '5d980bf203fd')
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_gc_validation_metrics', 'processing_count')
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

