"""moving october cope survey to november

Revision ID: a233678becb4
Revises: 4d7e99e7b5b4
Create Date: 2020-10-16 14:33:43.141368

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql

from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = 'a233678becb4'
down_revision = '4d7e99e7b5b4'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    op.alter_column('participant_summary', 'questionnaire_on_cope_oct',
                    new_column_name='questionnaire_on_cope_nov', existing_type=mysql.SMALLINT(display_width=6))
    op.alter_column('participant_summary', 'questionnaire_on_cope_oct_authored',
                    new_column_name='questionnaire_on_cope_nov_authored', existing_type=mysql.DATETIME())
    op.alter_column('participant_summary', 'questionnaire_on_cope_oct_time',
                    new_column_name='questionnaire_on_cope_nov_time', existing_type=mysql.DATETIME())


def downgrade_rdr():
    op.alter_column('participant_summary', 'questionnaire_on_cope_nov',
                    new_column_name='questionnaire_on_cope_oct', existing_type=mysql.SMALLINT(display_width=6))
    op.alter_column('participant_summary', 'questionnaire_on_cope_nov_authored',
                    new_column_name='questionnaire_on_cope_oct_authored', existing_type=mysql.DATETIME())
    op.alter_column('participant_summary', 'questionnaire_on_cope_nov_time',
                    new_column_name='questionnaire_on_cope_oct_time', existing_type=mysql.DATETIME())


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
