"""genomic_aw1_raw

Revision ID: a41c2f2266cb
Revises: 2580fc55edb9
Create Date: 2021-02-09 14:55:38.483257

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = 'a41c2f2266cb'
down_revision = '2580fc55edb9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genomic_aw1_raw',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('modified', sa.DateTime(), nullable=True),
        sa.Column('file_path', sa.String(length=255), nullable=True),
        sa.Column('ignore_flag', sa.SmallInteger(), nullable=False),
        sa.Column('dev_note', sa.String(length=255), nullable=True),
        sa.Column('package_id', sa.String(length=255), nullable=True),
        sa.Column('biobankid_sample_id', sa.String(length=255), nullable=True),
        sa.Column('box_storageunit_id', sa.String(length=255), nullable=True),
        sa.Column('box_id_plate_id', sa.String(length=255), nullable=True),
        sa.Column('well_position', sa.String(length=255), nullable=True),
        sa.Column('sample_id', sa.String(length=255), nullable=True),
        sa.Column('parent_sample_id', sa.String(length=255), nullable=True),
        sa.Column('collection_tube_id', sa.String(length=255), nullable=True),
        sa.Column('matrix_id', sa.String(length=255), nullable=True),
        sa.Column('collection_date', sa.String(length=255), nullable=True),
        sa.Column('biobank_id', sa.String(length=255), nullable=True),
        sa.Column('sex_at_birth', sa.String(length=255), nullable=True),
        sa.Column('age', sa.String(length=255), nullable=True),
        sa.Column('ny_state', sa.String(length=255), nullable=True),
        sa.Column('sample_type', sa.String(length=255), nullable=True),
        sa.Column('treatments', sa.String(length=255), nullable=True),
        sa.Column('quantity', sa.String(length=255), nullable=True),
        sa.Column('total_concentration', sa.String(length=255), nullable=True),
        sa.Column('total_dna', sa.String(length=255), nullable=True),
        sa.Column('visit_description', sa.String(length=255), nullable=True),
        sa.Column('sample_source', sa.String(length=255), nullable=True),
        sa.Column('study', sa.String(length=255), nullable=True),
        sa.Column('tracking_number', sa.String(length=255), nullable=True),
        sa.Column('contact', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('study_pi', sa.String(length=255), nullable=True),
        sa.Column('test_name', sa.String(length=255), nullable=True),
        sa.Column('failure_mode', sa.String(length=255), nullable=True),
        sa.Column('failure_mode_desc', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genomic_aw1_raw_file_path'), 'genomic_aw1_raw', ['file_path'], unique=False)
    op.create_index(op.f('ix_genomic_manifest_file_file_path'), 'genomic_manifest_file', ['file_path'], unique=False)
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genomic_manifest_file_file_path'), table_name='genomic_manifest_file')
    op.drop_index(op.f('ix_genomic_aw1_raw_file_path'), table_name='genomic_aw1_raw')
    op.drop_table('genomic_aw1_raw')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
