"""genomic_set_member_history_lengths

Revision ID: a6c3846e5eae
Revises: 00786d61be2e
Create Date: 2021-04-01 16:20:31.132972

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a6c3846e5eae'
down_revision = '00786d61be2e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN sequencing_file_name varchar(255) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_box_storage_unit_id varchar(255) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_box_plate_id varchar(255) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_study varchar(255) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_tracking_number varchar(255) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_contact varchar(255) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_email varchar(255) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_study_pi varchar(255) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_test_name varchar(255) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_failure_description varchar(255) null')
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN sequencing_file_name varchar(128) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_box_storage_unit_id varchar(50) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_box_plate_id varchar(50) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_study varchar(50) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_tracking_number varchar(50) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_contact varchar(50) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_email varchar(50) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_study_pi varchar(50) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_test_name varchar(50) null')
    op.execute('ALTER TABLE genomic_set_member_history MODIFY COLUMN gc_manifest_failure_description varchar(128) null')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
