"""ehr-metrics-use-organizations

Revision ID: ac995f0b54b8
Revises: 03bdb0a44083
Create Date: 2019-03-28 14:37:16.010194

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ac995f0b54b8"
down_revision = "03bdb0a44083"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ehr_receipt", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.drop_constraint("ehr_receipt_ibfk_1", "ehr_receipt", type_="foreignkey")
    op.create_foreign_key(
        None, "ehr_receipt", "organization", ["organization_id"], ["organization_id"], ondelete="CASCADE"
    )
    op.drop_column("ehr_receipt", "hpo_id")
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ehr_receipt", sa.Column("hpo_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "ehr_receipt", type_="foreignkey")
    op.create_foreign_key("ehr_receipt_ibfk_1", "ehr_receipt", "hpo", ["hpo_id"], ["hpo_id"], ondelete="CASCADE")
    op.drop_column("ehr_receipt", "organization_id")
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
