"""dv order history fix

Revision ID: b82e99329bf5
Revises: a43f72b7c848
Create Date: 2019-04-22 14:27:02.384999

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b82e99329bf5"
down_revision = "a43f72b7c848"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE biobank_dv_order_history CHANGE COLUMN `created` `created` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6);"
    )
    op.execute(
        "ALTER TABLE biobank_dv_order_history CHANGE COLUMN `modified` `modified` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);"
    )
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
