"""change datatype for aligned_q30_bases

Revision ID: baa91c8a684e
Revises: b3a08a8aca02
Create Date: 2020-11-04 09:21:23.897776

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'baa91c8a684e'
down_revision = 'b3a08a8aca02'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE genomic_gc_validation_metrics MODIFY COLUMN aligned_q30_bases BIGINT null')
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE genomic_gc_validation_metrics MODIFY COLUMN aligned_q30_bases int(11) null')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
