"""add is_creator for workspace user

Revision ID: c0394a487b8b
Revises: e8b090aa164e
Create Date: 2020-05-08 14:39:52.677433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0394a487b8b'
down_revision = 'e8b090aa164e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workbench_workspace_approved', 'name',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('workbench_workspace_snapshot', 'name',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.add_column('workbench_workspace_user', sa.Column('is_creator', sa.Boolean(), nullable=True))
    op.add_column('workbench_workspace_user_history', sa.Column('is_creator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbench_workspace_user_history', 'is_creator')
    op.drop_column('workbench_workspace_user', 'is_creator')
    op.alter_column('workbench_workspace_snapshot', 'name',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('workbench_workspace_approved', 'name',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
