"""add enrollment site to participant table

Revision ID: c069abb92cc0
Revises: df7c40b6a209
Create Date: 2020-08-18 20:59:18.237666

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = 'c069abb92cc0'
down_revision = 'df7c40b6a209'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name):
    globals()[f"downgrade_{engine_name}"]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('enrollment_site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant', 'site', ['enrollment_site_id'], ['site_id'])
    op.add_column('participant_history', sa.Column('enrollment_site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant_history', 'site', ['enrollment_site_id'], ['site_id'])

    op.add_column('site', sa.Column('site_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'site_type')
    op.drop_constraint(None, 'participant_history', type_='foreignkey')
    op.drop_column('participant_history', 'enrollment_site_id')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'enrollment_site_id')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
