"""edit_expo_models

Revision ID: c33b3da0905a
Revises: 5fb55e871222
Create Date: 2024-06-12 15:43:39.957031

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'c33b3da0905a'
down_revision = '5fb55e871222'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exposomics_m1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', rdr_service.model.utils.UTCDateTime(), nullable=True),
    sa.Column('modified', rdr_service.model.utils.UTCDateTime(), nullable=True),
    sa.Column('biobank_id', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('row_data', mysql.JSON(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('bucket_name', sa.String(length=128), nullable=False),
    sa.Column('copied_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exposomics_m1_biobank_id'), 'exposomics_m1', ['biobank_id'], unique=False)
    op.create_index(op.f('ix_exposomics_m1_bucket_name'), 'exposomics_m1', ['bucket_name'], unique=False)
    op.create_index(op.f('ix_exposomics_m1_file_path'), 'exposomics_m1', ['file_path'], unique=False)
    op.add_column('exposomics_m0', sa.Column('biobank_id', sa.String(length=255), nullable=False))
    op.add_column('exposomics_m0', sa.Column('row_data', mysql.JSON(), nullable=False))
    op.create_index(op.f('ix_exposomics_m0_biobank_id'), 'exposomics_m0', ['biobank_id'], unique=False)
    op.drop_column('exposomics_m0', 'file_data')
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposomics_m0', sa.Column('file_data', mysql.JSON(), nullable=False))
    op.drop_index(op.f('ix_exposomics_m0_biobank_id'), table_name='exposomics_m0')
    op.drop_column('exposomics_m0', 'row_data')
    op.drop_column('exposomics_m0', 'biobank_id')
    op.drop_index(op.f('ix_exposomics_m1_file_path'), table_name='exposomics_m1')
    op.drop_index(op.f('ix_exposomics_m1_bucket_name'), table_name='exposomics_m1')
    op.drop_index(op.f('ix_exposomics_m1_biobank_id'), table_name='exposomics_m1')
    op.drop_table('exposomics_m1')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

