"""adding vcf tbi files to genomic gc metrics validation

Revision ID: c68d427d67b3
Revises: f80b79cff59e
Create Date: 2020-08-12 15:51:23.285273

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c68d427d67b3'
down_revision = 'f80b79cff59e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_gc_validation_metrics', sa.Column('vcf_tbi_path', sa.String(length=255), nullable=True))
    op.add_column('genomic_gc_validation_metrics', sa.Column('vcf_tbi_received', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_gc_validation_metrics', 'vcf_tbi_received')
    op.drop_column('genomic_gc_validation_metrics', 'vcf_tbi_path')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
