"""add_migration_for_aw3_manifest_run_id

Revision ID: c695b103a675
Revises: 807ea7985c8e, 040801e0cf50
Create Date: 2023-03-07 10:40:24.186911

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils


from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = 'c695b103a675'
down_revision = ('807ea7985c8e', '040801e0cf50')
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Update genomic_gc_validation_metrics
    Inner join genomic_set_member_id
        On genomic_set_member.id = genomic_gc_validation_metrics.genomic_set_member_id
    Set genomic_gc_validation_metrics.aw3_manifest_job_run_id = genomic_set_member.aw3_manifest_job_run_id
    Where genomic_gc_validation_metrics.pipeline_id = 'dragen_3.4.12'
    AND genomic_gc_validation_metrics.aw3_manifest_job_run_id is null
    AND genomic_set_member.aw3_manifest_job_run_id is not null
    AND genomic_set_member.genome_type = 'aou_wgs'
    """
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

