"""add enrollment status time to participant summary

Revision ID: c7c4b2f17f46
Revises: 147b312fe1c1
Create Date: 2018-10-31 11:34:00.788777

"""
from alembic import op
import sqlalchemy as sa
import model.utils


from participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from participant_enums import MetricSetType, MetricsKey
from model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus
from model.code import CodeType

# revision identifiers, used by Alembic.
revision = 'c7c4b2f17f46'
down_revision = '147b312fe1c1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_summary', sa.Column('enrollment_status_core_ordered_sample_time', model.utils.UTCDateTime(), nullable=True))
    op.add_column('participant_summary', sa.Column('enrollment_status_core_stored_sample_time', model.utils.UTCDateTime(), nullable=True))
    op.add_column('participant_summary', sa.Column('enrollment_status_member_time', model.utils.UTCDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_summary', 'enrollment_status_member_time')
    op.drop_column('participant_summary', 'enrollment_status_core_stored_sample_time')
    op.drop_column('participant_summary', 'enrollment_status_core_ordered_sample_time')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

