"""adding_member_to_long_read

Revision ID: d3ab710e8e87
Revises: 1103c6e3bd95, 785989447118
Create Date: 2024-04-02 13:08:53.950930

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3ab710e8e87'
down_revision = ('1103c6e3bd95', '785989447118')
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_long_read', sa.Column('genomic_set_member_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_genomic_long_read_genomic_set_member_id'), 'genomic_long_read', ['genomic_set_member_id'], unique=False)
    op.create_foreign_key(None, 'genomic_long_read', 'genomic_set_member', ['genomic_set_member_id'], ['id'])

    op.execute(
        """
        Update genomic_long_read
        Inner join genomic_set_member on genomic_set_member.biobank_id = genomic_long_read.biobank_id
            and genomic_set_member.genome_type = 'aou_wgs'
        Set genomic_long_read.genomic_set_member_id = genomic_set_member.id
        Where true
        """
    )
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genomic_long_read', type_='foreignkey')
    op.drop_index(op.f('ix_genomic_long_read_genomic_set_member_id'), table_name='genomic_long_read')
    op.drop_column('genomic_long_read', 'genomic_set_member_id')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

