"""add columns to metrics lifecycle cache

Revision ID: dd408c868dc6
Revises: 8b20451a84df
Create Date: 2019-03-12 10:16:38.513306

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd408c868dc6"
down_revision = "8b20451a84df"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE metrics_lifecycle_cache ADD COLUMN ppi_healthcare_access int(11) NOT NULL AFTER `ppi_lifestyle`;"
    )
    op.execute(
        "ALTER TABLE metrics_lifecycle_cache ADD COLUMN ppi_medical_history int(11) NOT NULL AFTER `ppi_healthcare_access`;"
    )
    op.execute(
        "ALTER TABLE metrics_lifecycle_cache ADD COLUMN ppi_medications int(11) NOT NULL AFTER `ppi_medical_history`;"
    )
    op.execute(
        "ALTER TABLE metrics_lifecycle_cache ADD COLUMN ppi_family_health int(11) NOT NULL AFTER `ppi_medications`;"
    )


# ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metrics_lifecycle_cache", "ppi_medications")
    op.drop_column("metrics_lifecycle_cache", "ppi_medical_history")
    op.drop_column("metrics_lifecycle_cache", "ppi_healthcare_access")
    op.drop_column("metrics_lifecycle_cache", "ppi_family_health")
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
