"""move dv change migration

Revision ID: de5a1383d6a1
Revises: ac995f0b54b8
Create Date: 2019-04-01 14:40:50.245905

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "de5a1383d6a1"
down_revision = "ac995f0b54b8"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_rdr():
    op.execute(
        "ALTER TABLE biobank_dv_order CHANGE COLUMN `created` `created` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);"
    )
    op.execute(
        "ALTER TABLE biobank_dv_order CHANGE COLUMN `modified` `modified` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);"
    )
    op.execute("ALTER TABLE biobank_dv_order CHANGE COLUMN `shipment_est_arrival` `shipment_est_arrival` DATETIME(6);")
    op.execute("ALTER TABLE biobank_dv_order CHANGE COLUMN `shipment_last_update` `shipment_last_update` DATETIME(6);")
    op.execute("ALTER TABLE biobank_dv_order CHANGE COLUMN `order_date` `order_date` DATETIME(6);")


def downgrade_rdr():
    op.execute("ALTER TABLE biobank_dv_order CHANGE COLUMN `created` `created` DATE NOT NULL DEFAULT CURRENT_DATE;")
    op.execute(
        "ALTER TABLE biobank_dv_order CHANGE COLUMN `modified` `modified` DATE NOT NULL DEFAULT CURRENT_DATE ON UPDATE CURRENT_DATE;"
    )
    op.execute("ALTER TABLE biobank_dv_order CHANGE COLUMN `shipment_est_arrival` `shipment_est_arrival` DATE;")
    op.execute("ALTER TABLE biobank_dv_order CHANGE COLUMN `shipment_last_update` `shipment_last_update` DATE;")
    op.execute("ALTER TABLE biobank_dv_order CHANGE COLUMN `order_date` `order_date` DATE;")


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
