"""core data flag for participant summary

Revision ID: e3042e3657de
Revises: fadfdc1147bf, 5101accaacee
Create Date: 2023-06-06 11:29:49.443343

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql

from rdr_service.participant_enums import PhysicalMeasurementsStatus, QuestionnaireStatus, OrderStatus
from rdr_service.participant_enums import WithdrawalStatus, WithdrawalReason, SuspensionStatus, QuestionnaireDefinitionStatus
from rdr_service.participant_enums import EnrollmentStatus, Race, SampleStatus, OrganizationType, BiobankOrderStatus
from rdr_service.participant_enums import OrderShipmentTrackingStatus, OrderShipmentStatus
from rdr_service.participant_enums import MetricSetType, MetricsKey, GenderIdentity
from rdr_service.model.base import add_table_history_table, drop_table_history_table
from rdr_service.model.code import CodeType
from rdr_service.model.site_enums import SiteStatus, EnrollingStatus, DigitalSchedulingStatus, ObsoleteStatus

# revision identifiers, used by Alembic.
revision = 'e3042e3657de'
down_revision = ('fadfdc1147bf', '5101accaacee')
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    op.add_column('participant_summary', sa.Column('has_core_data', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('participant_summary', sa.Column('has_core_data_time', rdr_service.model.utils.UTCDateTime(), nullable=True))


def downgrade_rdr():
    op.drop_column('participant_summary', 'has_core_data_time')
    op.drop_column('participant_summary', 'has_core_data')


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

