"""Create participant_research_ids table

Revision ID: f5465ad50121
Revises: 453145e73e93
Create Date: 2025-09-23 09:19:19.953789

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5465ad50121'
down_revision = '453145e73e93'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_research_ids',
    sa.Column('participant_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created', rdr_service.model.utils.UTCDateTime(), nullable=False),
    sa.Column('modified', rdr_service.model.utils.UTCDateTime(), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('controlled_tier_id', sa.Integer(), nullable=True),
    sa.Column('registered_tier_id', sa.Integer(), nullable=True),
    sa.Column('controlled_tier_plus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.participant_id'], ),
    sa.PrimaryKeyConstraint('participant_id'),
    sa.UniqueConstraint('controlled_tier_id'),
    sa.UniqueConstraint('controlled_tier_plus_id'),
    sa.UniqueConstraint('registered_tier_id'),
    sa.UniqueConstraint('research_id')
    )
    # ### end Alembic commands ###


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_research_ids')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

