"""updating enrollment status: removing 3.1 and adding 3.2

Revision ID: fadfdc1147bf
Revises: 5760b82285c8
Create Date: 2023-06-05 10:43:24.604959

"""
from alembic import op
import sqlalchemy as sa
import rdr_service.model.utils
from sqlalchemy.dialects import mysql

from rdr_service.participant_enums import EnrollmentStatusV32

# revision identifiers, used by Alembic.
revision = 'fadfdc1147bf'
down_revision = '5760b82285c8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_rdr():
    # Replace 3.1 status columns with 3.2
    op.drop_column('participant_summary', 'enrollment_status_v_3_1')
    op.add_column(
        'participant_summary',
        sa.Column('enrollment_status_v_3_2', rdr_service.model.utils.Enum(EnrollmentStatusV32), nullable=True)
    )

    # Replace PARTICIPANT timestamp
    op.drop_column('participant_summary', 'enrollment_status_participant_v_3_1_time')
    op.add_column(
        'participant_summary',
        sa.Column('enrollment_status_participant_v_3_2_time', rdr_service.model.utils.UTCDateTime(), nullable=True)
    )

    # Replace PARTICIPANT_PLUS_EHR timestamp
    op.drop_column('participant_summary', 'enrollment_status_participant_plus_ehr_v_3_1_time')
    op.add_column(
        'participant_summary',
        sa.Column(
            'enrollment_status_participant_plus_ehr_v_3_2_time',
            rdr_service.model.utils.UTCDateTime(),
            nullable=True
        )
    )

    # Replace PARTICIPANT_PLUS_BASICS timestamp (and rename to ENROLLED_PARTICIPANT)
    op.drop_column('participant_summary', 'enrollment_status_participant_plus_basics_v_3_1_time')
    op.add_column(
        'participant_summary',
        sa.Column(
            'enrollment_status_enrolled_participant_v_3_2_time',
            rdr_service.model.utils.UTCDateTime(),
            nullable=True
        )
    )

    # Replace CORE_MINUS_PM timestamp
    op.drop_column('participant_summary', 'enrollment_status_core_minus_pm_v_3_1_time')
    op.add_column(
        'participant_summary',
        sa.Column('enrollment_status_core_minus_pm_v_3_2_time', rdr_service.model.utils.UTCDateTime(), nullable=True)
    )

    # Replace CORE timestamp
    op.drop_column('participant_summary', 'enrollment_status_core_v_3_1_time')
    op.add_column(
        'participant_summary',
        sa.Column('enrollment_status_core_v_3_2_time', rdr_service.model.utils.UTCDateTime(), nullable=True)
    )

    # Remove PARTICIPANT_PLUS_BASELINE timestamp
    op.drop_column('participant_summary', 'enrollment_status_participant_plus_baseline_v_3_1_time')


def downgrade_rdr():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_summary', sa.Column('enrollment_status_participant_plus_baseline_v_3_1_time', mysql.DATETIME(), nullable=True))
    op.add_column('participant_summary', sa.Column('enrollment_status_participant_v_3_1_time', mysql.DATETIME(), nullable=True))
    op.add_column('participant_summary', sa.Column('enrollment_status_core_v_3_1_time', mysql.DATETIME(), nullable=True))
    op.add_column('participant_summary', sa.Column('enrollment_status_participant_plus_ehr_v_3_1_time', mysql.DATETIME(), nullable=True))
    op.add_column('participant_summary', sa.Column('enrollment_status_v_3_1', mysql.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('participant_summary', sa.Column('enrollment_status_participant_plus_basics_v_3_1_time', mysql.DATETIME(), nullable=True))
    op.add_column('participant_summary', sa.Column('enrollment_status_core_minus_pm_v_3_1_time', mysql.DATETIME(), nullable=True))
    op.drop_column('participant_summary', 'enrollment_status_v_3_2')
    op.drop_column('participant_summary', 'enrollment_status_participant_v_3_2_time')
    op.drop_column('participant_summary', 'enrollment_status_participant_plus_ehr_v_3_2_time')
    op.drop_column('participant_summary', 'enrollment_status_enrolled_participant_v_3_2_time')
    op.drop_column('participant_summary', 'enrollment_status_core_v_3_2_time')
    op.drop_column('participant_summary', 'enrollment_status_core_minus_pm_v_3_2_time')
    # ### end Alembic commands ###


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

