"""Filter test participants

Revision ID: ffcd82a35890
Revises: 9b70eae79af0
Create Date: 2017-08-15 16:17:22.245919

"""

# revision identifiers, used by Alembic.
revision = "ffcd82a35890"
down_revision = "9b70eae79af0"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"upgrade_{engine_name}"]()
    else:
        pass


def downgrade(engine_name):
    if engine_name == "rdr" or engine_name == "metrics":
        globals()[f"downgrade_{engine_name}"]()
    else:
        pass


def upgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_metrics():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_rdr():
    # View is replaced entirely in later migration.
    pass


def downgrade_rdr():
    pass
