CREATE DATABASE IF NOT EXISTS ${db_name} CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS '${READONLY_DB_USER}'@'%' IDENTIFIED BY '${READONLY_PASSWORD}';
CREATE USER IF NOT EXISTS '${RDR_DB_USER}'@'%' IDENTIFIED BY '${RDR_PASSWORD}';
CREATE USER IF NOT EXISTS '${ALEMBIC_DB_USER}'@'%' IDENTIFIED BY '${RDR_PASSWORD}';

