from sqlalchemy import Column, BigInteger, Integer, String, Date, event
from sqlalchemy.dialects.mysql import JSON

from rdr_service.model.utils import UTCDateTime
from rdr_service.model.base import (
    model_insert_listener,
    model_update_listener,
    PPSCBase,
)

MVP_FIELDS = [
    "primaryLanguage",
    "genderIdentity",
    "awardee",
    "isEhrDataAvailable",
    "aian",
    "questionnaireOnOverallHealth",
    "questionnaireOnOverallHealthAuthored",
    "questionnaireOnLifestyle",
    "questionnaireOnLifestyleAuthored",
    "questionnaireOnTheBasics",
    "questionnaireOnTheBasicsAuthored",
    "questionnaireOnHealthcareAccess",
    "questionnaireOnHealthcareAccessAuthored",
    "questionnaireOnSocialDeterminantsOfHealth",
    "questionnaireOnSocialDeterminantsOfHealthAuthored",
    "questionnaireOnPersonalAndFamilyHealthHistory",
    "questionnaireOnPersonalAndFamilyHealthHistoryAuthored",
    "questionnaireOnLifeFunctioning",
    "questionnaireOnLifeFunctioningAuthored",
    "questionnaireOnEmotionalHealthHistoryAndWellBeing",
    "questionnaireOnEmotionalHealthHistoryAndWellBeingAuthored",
    "questionnaireOnBehavioralHealthAndPersonality",
    "questionnaireOnBehavioralHealthAndPersonalityAuthored",
]


class AwardeeInSite(PPSCBase):
    __tablename__ = "awardee_insite"

    internal_fields = ["id", "created", "modified"]

    id = Column("id", Integer, autoincrement=True, primary_key=True)
    created = Column("created", UTCDateTime)
    modified = Column("modified", UTCDateTime)

    participantId = Column("participant_id", BigInteger, nullable=False)
    """
    PMI-specific ID generated by the RDR and used for tracking/linking participant data.
    Human-readable 10-character string beginning with P.
    """

    firstName = Column("first_name", String(255), nullable=True)
    """The first name of the participant."""
    middleName = Column("middle_name", String(255), nullable=True)
    """The middle name of the participant."""
    lastName = Column("last_name", String(255), nullable=True)
    """The last name of the participant."""
    zipCode = Column("zip_code", String(10), nullable=True)
    """The postal zip code of the participant."""
    state = Column("state", String(255), nullable=True)
    """The state the participant lives in."""
    city = Column("city", String(255), nullable=True)
    """The city the participant lives in."""
    streetAddress = Column("street_address", String(255), nullable=True)
    """Line 1 of the street address the participant lives at."""
    streetAddress2 = Column("street_address2", String(255), nullable=True)
    """Line 2 of the street address the participant lives at. Absent if no line 2 given."""
    phoneNumber = Column("phone_number", String(80), nullable=True)
    """The phone number of the participant."""
    email = Column("email", String(255), nullable=True)
    """The email address participant provided to register."""
    dateOfBirth = Column("date_of_birth", Date, nullable=True)
    """The day the participant was born."""

    organization = Column("organization", String(255), nullable=True)
    """An organization a participant is paired with or UNSET if none."""

    withdrawalStatus = Column(
        "withdrawal_status", String(32), nullable=False, default="not_withdrawn"
    )
    """
    Indicates whether the participant has withdrawn from the study and does not want their data used in future.

    Values:

    * not_withdrawn
    * withdrawn
    """
    withdrawalTime = Column("withdrawal_time", UTCDateTime, nullable=True)
    """The actual date and time at which the participant chose to stop participating in the Participant Portal."""

    deactivationStatus = Column(
        "deactivation_status", String(32), nullable=False, default="not_deactivated"
    )
    """
    Indicates whether the participant has indicated they do not want to be contacted anymore;
    also shouldn’t have any EHR data transferred after the given suspension date.

    Values:

    * not_deactivated
    * deactivated
    """
    deactivationTime = Column("deactivation_time", UTCDateTime, nullable=True)
    """
    The date and time at which the participant has indicated they do not want to be contacted anymore;
    also shouldn’t have any EHR data transferred after the given suspension date.
    """

    deceasedStatus = Column(
        "deceased_status", String(32), nullable=False, default="unset"
    )
    """
    Indicates whether the participant has a pending or approved deceased report.

    Values:

    * Pending = pending report
    * Deceased = report approved
    * unset = no deceased report or a denied deceased report
    """
    deceasedAuthored = Column("deceased_authored", UTCDateTime, nullable=True)
    """
    The UTC timestamp of when the report was entered into an external system,
    or when it was approved externally if it has been approved.
    """

    clinicPhysicalMeasurementsStatus = Column(
        "clinic_physical_measurements_status",
        String(32),
        nullable=False,
        default="unset",
    )
    """
    Indicates whether this participant has completed physical measurements.

    Values:

    * unset
    * Completed
    * Cancelled
    """
    clinicPhysicalMeasurementsFinalizedTime = Column(
        "clinic_physical_measurements_finalized_time", UTCDateTime, nullable=True
    )
    """Indicates the latest time physical measurements were finalized for the participant."""
    clinicPhysicalMeasurementsFinalizedSite = Column(
        "clinic_physical_measurements_finalized_site", String(255), nullable=True
    )
    """An indicator for the site where the physical measurements were finalized for each participant."""

    selfReportedPhysicalMeasurementsStatus = Column(
        "self_reported_physical_measurements_status",
        String(32),
        nullable=False,
        default="unset",
    )
    """
    Indicates whether this participant has completed self-reported physical measurements.

    Values:

    * unset
    * Completed
    * Cancelled
    """
    selfReportedPhysicalMeasurementsAuthored = Column(
        "self_reported_physical_measurements_authored", UTCDateTime, nullable=True
    )
    """Indicates the latest time the participant authored the survey for self-reporting physical measurements."""

    consentForElectronicHealthRecords = Column(
        "consent_for_electronic_health_records",
        String(10),
        nullable=False,
        default="no",
    )
    """
    Indicates whether electronic health records (EHR) consent has been received. If an EHR authorization has expired,
    the value will be set back to no.

    Values:

    * yes
    * no
    """
    consentForElectronicHealthRecordsAuthored = Column(
        "consent_for_electronic_health_records_authored", UTCDateTime, nullable=True
    )
    """
    Indicates the latest time at which the participant completed consent with the answer indicated in the status field.
    """
    consentForElectronicHealthRecordsFirstYesAuthored = Column(
        "consent_for_electronic_health_records_first_yes_authored",
        UTCDateTime,
        nullable=True,
    )
    """Indicates the first time at which the participant consented with Yes"""

    firstEhrReceiptTime = Column("first_ehr_receipt_time", UTCDateTime, nullable=True)
    """UTC timestamp indicating when RDR was first made aware of signed and uploaded EHR documents"""
    latestEhrReceiptTime = Column("latest_ehr_receipt_time", UTCDateTime, nullable=True)
    """UTC timestamp indicating the latest time RDR was aware of signed and uploaded EHR documents"""

    consentForStudyEnrollment = Column(
        "consent_for_study_enrollment", String(10), nullable=False, default="no"
    )
    """
    Indicates whether enrollment consent, or pediatric permission, has been received.

    Values:

    * yes
    * no
    """
    consentForStudyEnrollmentAuthored = Column(
        "consent_for_study_enrollment_authored", UTCDateTime, nullable=True
    )
    """
    The UTC date time of the latest time the participant, or a guardian, completed the necessary consent/permission
    forms to be considered consented for study enrollment.
    """

    patientStatus = Column("patient_status", JSON, nullable=True, default=list())
    """
    A flag available for sites of in person enrollment. A participant can have a status from multiple sites.  Example:

    .. code-block:: json

        "patientStatus": {
            “PITT_UPMC”: “YES”,
            “PITT_TEMPLE”: “NO_ACCESS”,
            “PITT_SOMETHING”: “NO”
        }

    .. note::
        The following values are available.

        * Yes: Confirmed in EHR system.
        * No: Not found in EHR system.
        * No Access: Unable to check EHR system.
        * Unknown: Inconclusive search results.
        * Not Applicable (will apply to DVs only).
    """

    enrollmentStatus = Column("enrollment_status", String(32), nullable=True)
    """
    Participant’s most recently obtained enrollment status. Statuses are defined by the current data glossary.

    Values:

    * registered
    * participant
    * participant_ehr_consent
    * enrolled
    * pmb_eligibile
    * core_minus_pm
    * core_participant
    """
    biospecimenSourceSite = Column(
        "biospecimen_source_site", String(255), nullable=True
    )
    """The site where the biospecimens were initially created for the participant"""
    biospecimenOrderTime = Column("biospecimen_order_time", UTCDateTime, nullable=True)
    """The first time at which the biospecimens were finalized in UTC."""
    biospecimenStatus = Column(
        "biospecimen_status", String(255), nullable=False, default="unset"
    )
    """
    An indicator for whether biospecimens have been finalized for the participant

    Values:

    * unset
    * created
    * collected
    * processed
    * finalized
    """

    sample1SAL2CollectionMethod = Column(
        "sample_1sal2_collection_method", String(255), nullable=False, default="unset"
    )
    """
    Gives how the 1SAL2 sample was collected (ie on site or using a mail kit)

    Values:

    * unset
    * mail_kit
    * on_site
    """
    sampleStatus1SAL2 = Column(
        "sample_status_1sal2", String(255), nullable=False, default="unset"
    )
    """
    The result of biobank processing on sample 1SAL2.

    Values:

    * unset
    * received
    * disposed
    * consumed
    * unknown
    * sample_not_received
    * sample_not_processed
    * accessinging_error
    * lab_accident
    * qns_for_processing
    * quality_issue
    """
    sampleOrderStatus1SAL2 = Column(
        "sample_order_status_1sal2", String(255), nullable=False, default="unset"
    )
    """
    The individual order status of sample 1SAL2.

    Values:

    * unset
    * created
    * collected
    * processed
    * finalized
    """
    sampleOrderStatus1SAL2Time = Column(
        "sample_order_status_1sal2_time", UTCDateTime, nullable=True
    )
    """The time the sample was marked as finalized by the processing site."""

    primaryLanguage = Column("primary_language", String(32), nullable=True)
    """
    Indicates the language of the consent that the participant signed.

    Values:

    * en
    * es
    """

    genderIdentity = Column("gender_identity", String(255), nullable=True)
    """
    The personal sense of one's own gender. It can correlate with assigned sex at birth or can differ from it.

    Values:

    * PMI_Skip
    * GenderIdentity_Man
    * GenderIdentity_Woman
    * GenderIdentity_NonBinary
    * GenderIdentity_Transgender
    * GenderIdentity_AdditionalOptions
    * GenderIdentity_PreferNotToAnswer
    * PMI_PreferNotToAnswer
    """

    awardee = Column("awardee", String(255), nullable=True)
    """Name of the HPO."""

    isEhrDataAvailable = Column(
        "is_ehr_data_available",
        String(10),
        nullable=True,
    )
    """
    Indicates whether Electronic Health Records (EHR) are currently present for the participant.
    This can be both participant mediated or HPO provided.

    Values:

    * yes
    * no
    """

    aian = Column("aian", String(32), nullable=True)
    """Denotes if the participants race is AI_AN (AMERICAN_INDIAN_OR_ALASKA_NATIVE)."""

    questionnaireOnOverallHealth = Column(
        "questionnaire_on_overall_health",
        String(64),
        nullable=True,
    )
    """
    Indicates status for Overall Health questionnaire.

    Values:

    * submitted_complete
    * submitted_incomplete
    """
    questionnaireOnOverallHealthAuthored = Column(
        "questionnaire_on_overall_health_authored", UTCDateTime, nullable=True
    )
    """Indicates the time at which the participant completed the overall health questionnaire."""

    questionnaireOnLifestyle = Column(
        "questionnaire_on_lifestyle",
        String(64),
        nullable=True,
    )
    """
    Indicates the status of lifestyle questionnaire.

    Values:

    * submitted_complete
    * submitted_incomplete
    """
    questionnaireOnLifestyleAuthored = Column(
        "questionnaire_on_lifestyle_authored", UTCDateTime, nullable=True
    )
    """Indicates the time at which the participant completed the lifestyle questionnaire."""

    questionnaireOnTheBasics = Column(
        "questionnaire_on_the_basics",
        String(64),
        nullable=True,
    )
    """
    Indicates the status of TheBasics questionnaire.

    Values:

    * submitted_complete
    * submitted_incomplete
    """
    questionnaireOnTheBasicsAuthored = Column(
        "questionnaire_on_the_basics_authored", UTCDateTime, nullable=True
    )
    """Indicates the time at which the participant completed the basics questionnaire."""

    questionnaireOnHealthcareAccess = Column(
        "questionnaire_on_healthcare_access",
        String(64),
        nullable=True,
    )
    """
    Indicates the status of HealthcareAccess questionnaire.

    Values:

    * submitted_complete
    * submitted_incomplete
    """
    questionnaireOnHealthcareAccessAuthored = Column(
        "questionnaire_on_healthcare_access_authored", UTCDateTime, nullable=True
    )
    """Indicates the time at which the participant completed the health care access questionnaire."""

    questionnaireOnSocialDeterminantsOfHealth = Column(
        "questionnaire_on_social_determinants_of_health",
        String(64),
        nullable=True,
    )
    """
    Indicates the status of SocialDeterminantsOfHealth questionnaire.

    Values:

    * submitted_complete
    * submitted_incomplete
    """
    questionnaireOnSocialDeterminantsOfHealthAuthored = Column(
        "questionnaire_on_social_determinants_of_health_authored", UTCDateTime, nullable=True
    )
    """Indicates the time at which the participant completed the social determinants of health questionnaire."""

    questionnaireOnPersonalAndFamilyHealthHistory = Column(
        "questionnaire_on_personal_and_family_health_history",
        String(64),
        nullable=True,
    )
    """
    Indicates the status PersonalAndFamilyHealthHistory questionnaire.

    Values:

    * submitted_complete
    * submitted_incomplete
    """
    questionnaireOnPersonalAndFamilyHealthHistoryAuthored = Column(
        "questionnaire_on_personal_and_family_health_history_authored", UTCDateTime, nullable=True
    )
    """Indicates the time at which the participant completed the personal and family health history questionnaire."""

    questionnaireOnLifeFunctioning = Column(
        "questionnaire_on_life_functioning",
        String(64),
        nullable=True,
    )
    """
    Indicates the status of LifeFunctioning questionnaire.

    Values:

    * submitted_complete
    * submitted_incomplete
    """
    questionnaireOnLifeFunctioningAuthored = Column(
        "questionnaire_on_life_functioning_authored", UTCDateTime, nullable=True
    )
    """Indicates the time at which the participant completed the Life Functioning questionnaire."""

    questionnaireOnEmotionalHealthHistoryAndWellBeing = Column(
        "questionnaire_on_emotional_health",
        String(64),
        nullable=True,
    )
    """
    Indicates the status of EmotionalHealthHistoryAndWellBeing questionnaire.

    Values:

    * submitted_complete
    * submitted_incomplete
    """
    questionnaireOnEmotionalHealthHistoryAndWellBeingAuthored = Column(
        "questionnaire_on_emotional_health_authored", UTCDateTime, nullable=True
    )
    """
    Indicates the time at which the participant completed the Emotional Health History and Well Being questionnaire.
    """

    questionnaireOnBehavioralHealthAndPersonality = Column(
        "questionnaire_on_behavioral_health",
        String(64),
        nullable=True,
    )
    """
    Indicates the status of BehavioralHealthAndPersonality questionnaire.

    Values:

    * submitted_complete
    * submitted_incomplete
    """
    questionnaireOnBehavioralHealthAndPersonalityAuthored = Column(
        "questionnaire_on_behavioral_health_authored", UTCDateTime, nullable=True
    )
    """
    Indicates the time at which the participant completed the Behavioral Health & Personality questionnaire.
    """

    @classmethod
    def create_surrogate_key_sql(cls) -> str:
        """
        Generates a SQL string for computing a hash of concatenated column values.

        :return: A SQL string that computes the hash of the concatenated column values.
            Eg: >>> create_surrogate_key_sql()
            "FARM_FINGERPRINT(CONCAT(COALESCE(CAST(col1 AS STRING), ''), '|' , COALESCE(CAST(col2 AS STRING), '') ))"
        """
        keys = [
            column.key
            for column in AwardeeInSite.__table__.columns
            if column.key not in AwardeeInSite.internal_fields
        ]
        sql_string = (
            "FARM_FINGERPRINT(CONCAT("
            + ", ".join(
                (
                    f"COALESCE(CAST({key} AS STRING), ''), '|' "
                    if key != "patient_status"
                    else "TO_BASE64(CAST(TO_JSON_STRING(patient_status) AS BYTES)), '|' "
                )
                for key in keys
            ).rstrip(", '|' ")
            + "))"
        )
        return sql_string


event.listen(AwardeeInSite, "before_insert", model_insert_listener)
event.listen(AwardeeInSite, "before_update", model_update_listener)
